In [1]:
# Импорт библиотек
import numpy as np #для матричных вычислений
import pandas as pd #для анализа и предобработки данных
import matplotlib.pyplot as plt #для визуализации
import seaborn as sns #для визуализации

plt.style.use('seaborn-v0_8') #стиль отрисовки seaborn
sns.set_style("whitegrid")

%matplotlib inline

SEED = 42

import sklearn
# from sklearn import metrics #метрики
# from sklearn import model_selection #методы разделения и валидации
# from sklearn import linear_model #линейные модели
# from sklearn import tree #деревья решений

# from scipy import stats
# from statsmodels.stats.outliers_influence import variance_inflation_factor
# from sklearn.metrics import mean_squared_error, r2_score, make_scorer

# from sklearn.preprocessing import PolynomialFeatures, StandardScaler
# from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet

# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import cross_validate
# from sklearn.pipeline import Pipeline

import sympy

from sympy import (
    Symbol, 
    S,
    simplify, 
    latex,
    sin,
    cos,
    exp,
    log,
    sqrt,
    FiniteSet,
    Union,
    Interval,
    Contains,
    ConditionSet,
    Eq,
    solveset, solve,
    diff,
    limit,
    im,
    N,
    oo
)

from sympy.calculus.util import (
    function_range,
    continuous_domain
)

import scipy

from scipy.optimize import minimize, least_squares

from IPython.display import display, Markdown

import sys
import os
from pathlib import Path

# Определяем путь к директории ноутбука
# Простое решение: определяем папку, где находится файл ноутбука
notebook_dir = None

# Способ 1: Используем библиотеку ipynbname (самый надежный способ)
# Если библиотека не установлена, она будет установлена автоматически
try:
    import ipynbname
    nb_path = ipynbname.path()
    if nb_path:
        notebook_dir = str(Path(nb_path).parent.resolve())
except ImportError:
    # Устанавливаем библиотеку, если её нет
    import subprocess
    import sys
    print("📦 Устанавливаю библиотеку ipynbname для определения пути к ноутбуку...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "ipynbname", "-q"])
    import ipynbname
    nb_path = ipynbname.path()
    if nb_path:
        notebook_dir = str(Path(nb_path).parent.resolve())
except Exception as e:
    print(f"⚠️  Не удалось использовать ipynbname: {e}")

# Способ 2: Пробуем получить путь через IPython (запасной вариант)
if notebook_dir is None:
    try:
        from IPython import get_ipython
        ipython = get_ipython()
        if ipython is not None:
            if hasattr(ipython, 'start_dir'):
                notebook_dir = str(Path(ipython.start_dir).resolve())
    except:
        pass

# Способ 3: Если не удалось определить, выводим ошибку
if notebook_dir is None:
    print(f"❌ ОШИБКА: Не удалось определить папку ноутбука!")
    print(f"   Текущая рабочая директория: {os.getcwd()}")
    print(f"   Установите библиотеку: pip install ipynbname")
    raise RuntimeError("Не удалось определить директорию ноутбука. Установите: pip install ipynbname")

# Выводим информацию для диагностики
print(f"📂 Директория ноутбука: {notebook_dir}")
print(f"📂 Текущая рабочая директория (до chdir): {os.getcwd()}")

# Добавляем путь к директории ноутбука в sys.path (в начало для приоритета)
if notebook_dir not in sys.path:
    sys.path.insert(0, notebook_dir)

# Меняем рабочую директорию на директорию ноутбука, чтобы относительные пути работали
os.chdir(notebook_dir)
print(f"📂 Рабочая директория установлена: {os.getcwd()}")

# Импортируем helper (если существует)
try:
    from helper.functionanalyzer import FunctionAnalyzer
except ImportError:
    print("⚠️  Модуль helper.functionanalyzer не найден (это нормально, если он не используется)")


from tqdm import tqdm
import time

print(f'Numpy version {np.__version__}')
print(f'Pandas version {pd.__version__}')
print(f'sklearn version {sklearn.__version__}')
print(f'scipy version {scipy.__version__}')
print(f'sympy version {sympy.__version__}')

from sklearnex import patch_sklearn, config_context
patch_sklearn()

import cupy as cp

# Пробуем импортировать nvmath независимо от версии Python
# (модуль может быть обновлен и поддерживать более новые версии)
try:
    import nvmath
    print(f"✅ Модуль nvmath успешно импортирован (Python {sys.version_info.major}.{sys.version_info.minor})")
except ImportError as e:
    # Проверяем, связана ли ошибка с версией Python
    if sys.version_info >= (3, 13):
        print(f"⚠️  Модуль nvmath не установлен или не поддерживает Python {sys.version_info.major}.{sys.version_info.minor}")
        print(f"   Попробуйте обновить nvmath: pip install --upgrade nvmath")
        print(f"   Или используйте Python 3.12 или ниже для полной совместимости")
    else:
        print(f"⚠️  Модуль nvmath не установлен (Python {sys.version_info.major}.{sys.version_info.minor})")
        print(f"   Установите: pip install nvmath")
except Exception as e:
    print(f"⚠️  Ошибка при импорте nvmath: {e}")



📂 Директория ноутбука: C:\Users\stepu\OneDrive\IDE\skillfactory\Блок 6\MATH&ML-11. Кластеризация и техники понижения размерности. Часть II
📂 Текущая рабочая директория (до chdir): c:\Users\stepu\OneDrive\IDE
📂 Рабочая директория установлена: C:\Users\stepu\OneDrive\IDE\skillfactory\Блок 6\MATH&ML-11. Кластеризация и техники понижения размерности. Часть II
Numpy version 1.26.4
Pandas version 2.2.3
sklearn version 1.5.2
scipy version 1.15.1
sympy version 1.13.3


Intel(R) Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)


⚠️  Модуль nvmath не установлен или не поддерживает Python 3.13
   Попробуйте обновить nvmath: pip install --upgrade nvmath
   Или используйте Python 3.12 или ниже для полной совместимости


In [2]:
# настройка логгирования

%pip install loguru

from loguru import logger
from helper.logging_config import setup_logging
import logging

# Вызываем настройку в самом начале работы приложения
setup_logging()

# Уменьшаем уровень логирования для sklearn и sklearnex, чтобы убрать лишние INFO сообщения
logging.getLogger('sklearn').setLevel(logging.WARNING)
logging.getLogger('sklearnex').setLevel(logging.WARNING)
logging.getLogger('sklearn.utils.validation').setLevel(logging.WARNING)
logging.getLogger('sklearn.cluster').setLevel(logging.WARNING)

#user_id = 123
#status = "success"
# Привычный и читаемый синтаксис
#logger.info("Аутентификация для пользователя {id} прошла со статусом: {status}", id=user_id, status=status)

# @logger.catch
# def main_logic():
#     logger.info("Приложение начинает работу.")
#     # ... ваш основной код ...
#     a = 10
#     b = 0
#     result = a / b # Это вызовет ошибку, которую поймает @logger.catch

@logger.catch
def main_logic():
    logger.info("Приложение начинает работу.")
    
if __name__ == "__main__":
    main_logic()



14:02:43 | INFO     | helper.logging_config:setup_logging - Стандартный logging перехвачен.
14:02:43 | INFO     | helper.logging_config:setup_logging - Конфигурация логирования завершена.
14:02:43 | INFO     | __main__:main_logic - Приложение начинает работу.


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
import pandas as pd
A = np.matrix([[1,2,3,4],
               [5,5,6,7],
               [1,4,2,3],
               [5,3,2,1],
               [8,1,2,2]])

df = pd.DataFrame(A,columns  = ['x1','x2','x3','x4'])
df_std  = (df - df.mean()) / (df.std())

df_std

x1        x2        x3        x4
0 -1.000000 -0.632456  0.000000  0.260623
1  0.333333  1.264911  1.732051  1.563740
2 -1.000000  0.632456 -0.577350 -0.173749
3  0.333333  0.000000 -0.577350 -1.042493
4  1.333333 -1.264911 -0.577350 -0.608121

In [5]:
cov_mat = np.cov(df_std.T)
cov_mat

array([[ 1.        , -0.31622777,  0.04811252, -0.18098843],
       [-0.31622777,  1.        ,  0.63900965,  0.61812254],
       [ 0.04811252,  0.63900965,  1.        ,  0.94044349],
       [-0.18098843,  0.61812254,  0.94044349,  1.        ]])

In [6]:
eigen_val, eigen_vectors = np.linalg.eig(cov_mat)

display(eigen_val)
display(eigen_vectors)

array([2.51579324, 1.0652885 , 0.39388704, 0.02503121])

array([[ 0.16195986, -0.91705888, -0.30707099,  0.19616173],
       [-0.52404813,  0.20692161, -0.81731886,  0.12061043],
       [-0.58589647, -0.3205394 ,  0.1882497 , -0.72009851],
       [-0.59654663, -0.11593512,  0.44973251,  0.65454704]])

Теперь нам необходимо выбрать два собственных вектора, так как в итоге мы хотим получить две компоненты. Нужно взять векторы с наибольшими собственными значениями. При нахождении собственных векторов в Python они выводятся в соответствии с убыванием соответствующих собственных значений, поэтому берём первые два вектора:

In [10]:
first_two = eigen_vectors[:, :2]
first_two

#Как взять 2 первых вектора?


array([[ 0.16195986, -0.91705888],
       [-0.52404813,  0.20692161],
       [-0.58589647, -0.3205394 ],
       [-0.59654663, -0.11593512]])

Осталось только найти главные компоненты. Для этого перемножаем матрицу стандартизированных признаков на матрицу с собственными векторами и получаем матрицу главных компонент:

In [12]:
Matrix_PC = df_std @ first_two
Matrix_PC

0         1
0  0.014003  0.755975
1 -2.556534 -0.780432
2 -0.051480  1.253135
3  1.014150  0.000239
4  1.579861 -1.228917

В параметр n_components в качестве значения можно передать количество необходимых компонентов или минимально допустимую объяснённую дисперсию в виде десятичной дроби. Например, если нам нужно столько компонент, чтобы они объясняли не менее 90 % разброса данных, то мы запишем n_components = 0.9.

In [18]:
#импортируем нужный алгоритм

from sklearn.decomposition import PCA
#определяем метод главных компонент с двумя компонентами
pca = PCA(n_components=2)
#обучаем алгоритм на наших данных
principalComponents = pca.fit_transform(df_std)

# выводим результат
principalComponents
display(principalComponents)

# выводим дисперсию
display(pca.explained_variance_)

# выводим долю дисперсии
display(pca.explained_variance_ratio_)

# выводим сумму дисперсий
display(pca.explained_variance_ratio_.cumsum())



array([[-1.40033078e-02, -7.55974765e-01],
       [ 2.55653399e+00,  7.80431775e-01],
       [ 5.14801919e-02, -1.25313470e+00],
       [-1.01415002e+00, -2.38808310e-04],
       [-1.57986086e+00,  1.22891650e+00]])

array([2.51579324, 1.0652885 ])

array([0.62894831, 0.26632213])

array([0.62894831, 0.89527044])

## Задание 5.1
1 point possible (graded)
Найдите матрицу ковариаций для векторов (3, 4, 1) и (1, 6, 2) . В качестве ответа укажите сумму всех значений матрицы, округлённую до двух знаков после точки-разделителя.

In [19]:
# Задание 5.1: Матрица ковариаций для векторов (3, 4, 1) и (1, 6, 2)

# Создаём векторы
v1 = np.array([3, 4, 1])
v2 = np.array([1, 6, 2])

# Объединяем векторы в матрицу (каждая строка - это переменная)
# Для np.cov() нужно передать матрицу, где каждая строка - переменная, столбцы - наблюдения
data = np.array([v1, v2])

# Вычисляем матрицу ковариаций
cov_matrix = np.cov(data)

print("Матрица ковариаций:")
print(cov_matrix)
print()

# Находим сумму всех элементов матрицы
sum_cov = np.sum(cov_matrix)

print(f"Сумма всех значений матрицы: {sum_cov}")
print(f"Сумма всех значений матрицы (округлено до 2 знаков): {round(sum_cov, 2)}")

# Выводим результат
display(cov_matrix)
display(f"Ответ: {round(sum_cov, 2)}")


Матрица ковариаций:
[[2.33333333 2.5       ]
 [2.5        7.        ]]

Сумма всех значений матрицы: 14.333333333333332
Сумма всех значений матрицы (округлено до 2 знаков): 14.33


array([[2.33333333, 2.5       ],
       [2.5       , 7.        ]])

'Ответ: 14.33'

## Задание 5.4
1 point possible (graded)
Дана матрица признаков:
A = np.matrix([[8,7,2,9],
               [1,3,6,3],
               [7,2,0,3],
               [10,3,1,1],
               [8,1,3,4]])

Какое минимальное количество главных компонент надо выделить, чтобы сохранить информацию о как минимум 90 % разброса данных?

In [25]:
# Задание 5.4: Сравнение подходов - с стандартизацией и без

from sklearn.decomposition import PCA

# Создаём матрицу признаков
A = np.matrix([[8,7,2,9],
               [1,3,6,3],
               [7,2,0,3],
               [10,3,1,1],
               [8,1,3,4]])

print("=" * 80)
print("СРАВНЕНИЕ ПОДХОДОВ: БЕЗ СТАНДАРТИЗАЦИИ vs СО СТАНДАРТИЗАЦИЕЙ")
print("=" * 80)
print()

# ============================================================================
# ПОДХОД 1: БЕЗ СТАНДАРТИЗАЦИИ (мой первоначальный подход)
# ============================================================================
print("ПОДХОД 1: БЕЗ СТАНДАРТИЗАЦИИ")
print("-" * 80)

df_A = pd.DataFrame(A)

pca_no_std = PCA(n_components=0.9)
pca_no_std.fit(df_A)

min_components_no_std = pca_no_std.n_components_
print(f"Минимальное количество компонент: {min_components_no_std}")
print(f"Объяснённая дисперсия: {pca_no_std.explained_variance_ratio_.sum():.4f} ({pca_no_std.explained_variance_ratio_.sum()*100:.2f}%)")

# Детальный анализ
pca_all_no_std = PCA(n_components=None)
pca_all_no_std.fit(df_A)
cumsum_no_std = np.cumsum(pca_all_no_std.explained_variance_ratio_)

print("\nДоли объяснённой дисперсии (БЕЗ стандартизации):")
for i, (var_ratio, cum_var) in enumerate(zip(pca_all_no_std.explained_variance_ratio_, cumsum_no_std), 1):
    print(f"  Компонента {i}: {var_ratio:.4f} ({var_ratio*100:.2f}%), кумулятивно: {cum_var:.4f} ({cum_var*100:.2f}%)")

print()
print("=" * 80)

# ============================================================================
# ПОДХОД 2: СО СТАНДАРТИЗАЦИЕЙ (эталонное решение)
# ============================================================================
print("ПОДХОД 2: СО СТАНДАРТИЗАЦИЕЙ (эталонное решение)")
print("-" * 80)

df = pd.DataFrame(A)
df_std = (df - df.mean()) / (df.std())

print("Стандартизированные данные:")
print(df_std)
print()

pca_with_std = PCA(n_components=0.9)
pca_with_std.fit(df_std)

min_components_with_std = pca_with_std.n_components_
print(f"Минимальное количество компонент: {min_components_with_std}")
print(f"Объяснённая дисперсия: {pca_with_std.explained_variance_ratio_.sum():.4f} ({pca_with_std.explained_variance_ratio_.sum()*100:.2f}%)")

# Детальный анализ
pca_all_with_std = PCA(n_components=None)
pca_all_with_std.fit(df_std)
cumsum_with_std = np.cumsum(pca_all_with_std.explained_variance_ratio_)

print("\nДоли объяснённой дисперсии (СО стандартизацией):")
for i, (var_ratio, cum_var) in enumerate(zip(pca_all_with_std.explained_variance_ratio_, cumsum_with_std), 1):
    print(f"  Компонента {i}: {var_ratio:.4f} ({var_ratio*100:.2f}%), кумулятивно: {cum_var:.4f} ({cum_var*100:.2f}%)")

print()
print("=" * 80)
print("ИТОГОВОЕ СРАВНЕНИЕ:")
print("=" * 80)
print(f"БЕЗ стандартизации: {min_components_no_std} компонент(ы) для 90% дисперсии")
print(f"СО стандартизацией: {min_components_with_std} компонент(ы) для 90% дисперсии")
print()
print("=" * 80)
print("ВЫВОД:")
print("=" * 80)
print("""
В PCA стандартизация данных КРИТИЧЕСКИ ВАЖНА, потому что:

1. PCA основан на ковариационной матрице, которая чувствительна к масштабу признаков
2. Признаки с большими значениями будут доминировать в анализе
3. Без стандартизации PCA будет искать направления максимальной дисперсии в исходном масштабе,
   что может не отражать реальную структуру данных

ЭТАЛОННОЕ РЕШЕНИЕ ПРАВИЛЬНОЕ - нужно использовать стандартизацию!
""")

# Выводим итоговый ответ
display(Markdown(f"**✅ ПРАВИЛЬНЫЙ ОТВЕТ: минимальное количество главных компонент = {min_components_with_std}**"))
display(Markdown(f"*(при использовании стандартизации данных)*"))


СРАВНЕНИЕ ПОДХОДОВ: БЕЗ СТАНДАРТИЗАЦИИ vs СО СТАНДАРТИЗАЦИЕЙ

ПОДХОД 1: БЕЗ СТАНДАРТИЗАЦИИ
--------------------------------------------------------------------------------
Минимальное количество компонент: 2
Объяснённая дисперсия: 0.9092 (90.92%)

Доли объяснённой дисперсии (БЕЗ стандартизации):
  Компонента 1: 0.5050 (50.50%), кумулятивно: 0.5050 (50.50%)
  Компонента 2: 0.4042 (40.42%), кумулятивно: 0.9092 (90.92%)
  Компонента 3: 0.0500 (5.00%), кумулятивно: 0.9591 (95.91%)
  Компонента 4: 0.0409 (4.09%), кумулятивно: 1.0000 (100.00%)

ПОДХОД 2: СО СТАНДАРТИЗАЦИЕЙ (эталонное решение)
--------------------------------------------------------------------------------
Стандартизированные данные:
          0         1         2         3
0  0.350823  1.666410 -0.173749  1.666667
1 -1.695646 -0.087706  1.563740 -0.333333
2  0.058471 -0.526235 -1.042493 -0.333333
3  0.935529 -0.087706 -0.608121 -1.000000
4  0.350823 -0.964764  0.260623  0.000000

Минимальное количество компонент: 3
Объяснён

**✅ ПРАВИЛЬНЫЙ ОТВЕТ: минимальное количество главных компонент = 3**

*(при использовании стандартизации данных)*