In [1]:
# Импорт библиотек
import numpy as np #для матричных вычислений
import pandas as pd #для анализа и предобработки данных
import matplotlib.pyplot as plt #для визуализации
import seaborn as sns #для визуализации

plt.style.use('seaborn-v0_8') #стиль отрисовки seaborn
sns.set_style("whitegrid")

%matplotlib inline

SEED = 42

# from sklearn import metrics #метрики
# from sklearn import model_selection #методы разделения и валидации
# from sklearn import linear_model #линейные модели
# from sklearn import tree #деревья решений

# from scipy import stats
# from statsmodels.stats.outliers_influence import variance_inflation_factor
# from sklearn.metrics import mean_squared_error, r2_score, make_scorer

# from sklearn.preprocessing import PolynomialFeatures, StandardScaler
# from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet

# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import cross_validate
# from sklearn.pipeline import Pipeline


Найдите собственные числа и собственные вектора матрицы:

A = 3, 2
    1, 2


In [2]:
# создаем матрицу А
A = np.array([
    [3, 1],
    [2, 2]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [4. 1.]
Собственные векторы: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


Тут сразу возникают вопросы. Полученные собственные векторы вовсе не совпадают с тем, что мы получали в ручном счёте. Секрет в том, что в numpy при расчёте собственных векторов они автоматически нормализуются (как векторы) — приводятся к длине, равной 1. Если вы стандартизируете вектора, которые мы получали в теоретической части, вы получите ровно те же самые вектора. Можете проверить самостоятельно. Напомним, что стандартизацию векторов мы проходили в модуле MATH&ML-2. Линейная алгебра в контексте линейных методов ч. 2.

Найдите собственные числа матрицы:
     1   4   5
A = -5   8   9
    -6   7   11

In [3]:
# создаем матрицу А
A = np.array([
    [1, 4, 5],
    [-5, 8, 9 ],
    [-6, 7, 11]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [13.59373746  5.03209301  1.37416954]
Собственные векторы: 
 [[ 0.52589141 -0.88433329  0.16952613]
 [-0.49209425  0.2173033  -0.76227541]
 [-0.69374453  0.4131996   0.62465759]]


Найдём собственные числа заведомо вырожденной матрицы. 

      1  4   5   8
     -4 12  14  15
A =  -5  8   9   7
     -6  7   11  4 

In [4]:
# создаем матрицу А
A = np.array([
    [1, 4, 5, 8],
    [-4, 12, 14, 15],
    [-5, 8, 9, 7],
    [-6, 7, 11, 4]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [ 2.54687092e+01  1.53129080e+00  8.60299588e-15 -1.00000000e+00]
Собственные векторы: 
 [[-3.27938984e-01  8.35109112e-01  5.77350269e-01 -2.06372086e-01]
 [ 5.20981245e-01 -4.97100905e-01 -5.77350269e-01  3.71469755e-01]
 [ 6.45382646e-01  2.83373358e-02  5.77350269e-01 -8.25488343e-01]
 [ 4.52234237e-01  2.33838526e-01  3.01201371e-15  3.71469755e-01]]


Что видим? Одно из собственных чисел получилось равным 0. Это сигнал к тому, что строки или столбцы матрицы A являются линейно зависимыми, то есть матрица плохо обусловлена, а точнее — вырождена.

Найти собственные числа матрицы:

A  = 0  1
    -1  0

In [5]:
# создаем матрицу А
A = np.array([
    [0, 1],
    [-1, 0]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [0.+1.j 0.-1.j]
Собственные векторы: 
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


Опять магия! Результат есть. Только какой-то странный: что за +1.j и -1.j? Забегая вперёд, скажем, что это комплексные числа. Однако оставим эту интригу и разберёмся с ними чуть позже.

### Задание 4.1
3 points possible (ungraded)
Найдите собственные числа для матрицы:

     1   3    5
A =  4  -4    9
    13   7    12 

In [6]:
# создаем матрицу А
A = np.array([
    [1, 3, 5],
    [4, -4, 9],
    [13, 7, 12]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [19.52189628 -3.75422737 -6.76766891]
Собственные векторы: 
 [[-0.59065136 -0.9084069  -0.40394124]
 [-0.29844178 -0.16657961 -0.77823322]
 [-0.74970893  0.38346857  0.48081652]]


Задание 4.2
4 points possible (ungraded)
Найдите собственные числа матрицы Грама ATA, если:

     1    9    4     
A =  9    4    7
     4    7    12

In [9]:
# создаем матрицу А
A = np.array([
    [1, 9, 4],
    [9, 4, 7],
    [4, 7, 12]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A.T @ A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [391.37004987  45.77088847  15.85906166]
Собственные векторы: 
 [[-0.41955589 -0.7323045  -0.5363795 ]
 [-0.55709648  0.67425896 -0.48478693]
 [-0.71667034 -0.09541992  0.69085358]]


In [10]:
import numpy as np
x1 = np.array([1, 2, 1, 1]).T
x2 = np.array([70, 130, 65, 60]).T

C = np.array([[1, 0.9922], [0.9922, 1]])

eig_values, eig_vectors = np.linalg.eig(C)

x1_norm = (x1 - x1.mean()) / np.linalg.norm(x1)
x2_norm = (x2 - x2.mean()) / np.linalg.norm(x2)

x_new = x1_norm * eig_vectors[0][0] + x2_norm * eig_vectors[1][0]

x_new_norm = (x_new - x_new.mean()) / np.linalg.norm(x_new)

print(np.round(x_new_norm, 2))

## [-0.24  0.86 -0.29 -0.33]

[-0.24  0.86 -0.29 -0.33]
