In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[10,  9,  9],
       [ 9,  6,  8],
       [ 8,  5,  7]])

In [4]:
B

array([[-1,  3,  3],
       [ 3,  2, -1],
       [-1, -2,  2]])

In [5]:
# Поэлементное умножение
A*B

array([[-10,  27,  27],
       [ 27,  12,  -8],
       [ -8, -10,  14]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 8 30 39]
 [ 1 23 37]
 [ 0 20 33]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[ 8, 30, 39],
       [ 1, 23, 37],
       [ 0, 20, 33]])

In [8]:
# Матричное умножение
A@B

array([[ 8, 30, 39],
       [ 1, 23, 37],
       [ 0, 20, 33]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[ 41,  24,  36],
       [ 40,  34,  36],
       [-12, -11, -11]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 9  9  5  5  7]
 [ 5 10 11  9 10]
 [11  9 10  8  5]]
B:
 [[ 1  0]
 [-2 -2]
 [ 1  2]
 [ 3  3]
 [ 2  3]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[25, 28],
       [43, 59],
       [37, 41]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [13]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [14]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-2  2 -1 -3]
 [ 1 -1  2 -4]
 [ 0  1 -4 -4]
 [-2  1 -4  0]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-2  4  0  3]
 [ 1 -2  0  4]
 [ 0  2  0  4]
 [-2  2  0  0]]
DA:
 [[-2  2 -1 -3]
 [ 2 -2  4 -8]
 [ 0  0  0  0]
 [ 2 -1  4  0]]


In [15]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [16]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [17]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [18]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [19]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [20]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Задание 7.1

1 point possible (graded)

Даны матрица A и вектор х:

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
Найдите произведение матрицы A и вектора х в том порядке, в котором их можно умножить.

В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. Пример ввода ответа: 1,1.

26,30

In [23]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

print('A:\n',A)
print('x:\n',x)

A@x


A:
 [[ 5 -1  3  1  2]
 [-2  8  5 -1  1]]
x:
 [1 2 3 4 5]


array([26, 30])

### Задание 7.2

1 point possible (graded)

Даны две матрицы:

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
Найдите произведение матриц  A  и  B  в том порядке, в котором их можно умножить.

В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [26]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

print('A:\n',A) 
print('A.shape:\n', A.shape)
print('B:\n',B)
print('B.shape:\n', B.shape)

B@A


A:
 [[1 9 8 5]
 [3 6 3 2]
 [3 3 3 3]
 [0 2 5 9]
 [4 4 1 2]]
A.shape:
 (5, 4)
B:
 [[ 1 -1  0  1  1]
 [-2  0  2 -1  1]]
B.shape:
 (2, 5)


array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [29]:
def check_matrix_multiplication(A: np.ndarray, B: np.ndarray) -> tuple:
    """
    Проверяет возможность умножения матриц и определяет правильный порядок.
    
    Parameters:
    -----------
    A, B : np.ndarray
        Матрицы для проверки
        
    Returns:
    --------
    tuple
        (можно ли умножить, порядок умножения, размерность результата)
        Порядок умножения: 'AB' или 'BA' или None если умножение невозможно
    """
    
    # Получаем размерности матриц
    a_rows, a_cols = A.shape
    b_rows, b_cols = B.shape
    
    # Проверяем оба варианта умножения
    can_multiply_AB = a_cols == b_rows
    can_multiply_BA = b_cols == a_rows
    
    if can_multiply_AB and can_multiply_BA:
        # Если возможны оба варианта, возвращаем оба
        return True, ['AB', 'BA'], [(a_rows, b_cols), (b_rows, a_cols)]
    elif can_multiply_AB:
        return True, 'AB', (a_rows, b_cols)
    elif can_multiply_BA:
        return True, 'BA', (b_rows, a_cols)
    else:
        return False, None, None

def multiply_matrices(A: np.ndarray, B: np.ndarray) -> tuple:
    """
    Выполняет умножение матриц в правильном порядке, если это возможно.
    
    Parameters:
    -----------
    A, B : np.ndarray
        Матрицы для умножения
        
    Returns:
    --------
    tuple
        (результат умножения, использованный порядок)
        Если умножение невозможно, возвращает (None, None)
    """
    
    can_multiply, order, result_shape = check_matrix_multiplication(A, B)
    
    if not can_multiply:
        print(f"Умножение невозможно!")
        print(f"Размерности матриц: A{A.shape}, B{B.shape}")
        return None, None
    
    if isinstance(order, list):
        print(f"Возможны оба варианта умножения:")
        print(f"A×B -> размерность {result_shape[0]}")
        print(f"B×A -> размерность {result_shape[1]}")
        return [A @ B, B @ A], order
    
    result = B @ A if order == 'BA' else A @ B
    print(f"Выполнено умножение в порядке {order}")
    print(f"Размерность результата: {result.shape}")
    
    return result, order

# Пример использования:

# Создаем тестовые матрицы

# A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
# B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

A = np.array([[1, 9, 8, 5], 
              [3, 6, 3, 2], 
              [3, 3, 3, 3], 
              [0, 2, 5, 9], 
              [4, 4, 1, 2]])
    
B = np.array([[1, -1, 0, 1, 1], 
                [-2, 0, 2, -1, 1]])

# Проверяем возможность умножения
result, order = multiply_matrices(A, B)

if result is not None:
    print("\nРезультат:")
    print(result)
    print('Элемент четвертого столбца первой строки:', result[0][3])



Выполнено умножение в порядке BA
Размерность результата: (2, 4)

Результат:
[[  2   9  11  14]
 [  8 -10 -14 -11]]
Элемент четвертого столбца первой строки: 14


### Задание 7.3

1 point possible (graded)

Дана система векторов:

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Составьте матрицу  A , расположив векторы  x ,  y ,  z  в строках. Найдите матрицу Грама  G  (матрицу скалярных произведений столбцов матрицы  A ) системы векторов  x ,  y ,  z .

Чему равна полученная матрица Грама  G ?

In [30]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A=np.array([x,y,z])
print (A, type(A))

A.T@A






[[ 1  2  1  0  4]
 [ 2  1 -1  1  0]
 [-1  1 -1  0  0]] <class 'numpy.ndarray'>


array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

### Условие для заданий 7.4 и 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [34]:
import pandas as pd

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)



### Задание 7.4

1 point possible (graded)

Найдите вектор дохода салона по стилистам, если за каждую услугу стилисты платят салону определённую «комиссию».

Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).

Выберите координаты вектора прибыли салона:

In [38]:
# Вектор комиссий
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

Шаг 2: Расчет общего дохода по каждой услуге для каждого стилиста

Чтобы найти общий доход (выручку) по каждой услуге для каждого стилиста, нужно умножить количество услуг на их стоимость. Pandas позволяет сделать это поэлементно для DataFrame с одинаковыми индексами и колонками.

In [39]:
# Расчет выручки по каждой услуге для каждого стилиста
Total_Revenue_DF = Count_DF * Price_DF
print("Общая выручка по услугам (тыс. руб.):")
print(Total_Revenue_DF)
print("-" * 30)


Общая выручка по услугам (тыс. руб.):
       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               20.0              7.5         12.0     12.0  10.0
Борис              3.6             52.5          3.0     25.0   6.0
Вика              24.0             24.0          0.0     15.0   8.0
Галя               7.2              9.6         50.4     11.2  10.0
Дима              15.0             87.5         54.0     25.0  27.0
Егор              50.0             15.0          6.0     34.0  30.0
Женя              24.2              1.0          6.0     12.5  34.0
Юра               31.5              0.0         77.5     31.0  56.0
------------------------------


Шаг 3: Расчет дохода салона (комиссии) от каждого стилиста (Задание 7.4)

Доход салона от стилиста — это сумма комиссий, уплаченных стилистом со всех оказанных им услуг.
Сначала рассчитаем сумму комиссии по каждой услуге для каждого стилиста, умножив выручку по услуге (Total_Revenue_DF) на соответствующую ставку комиссии (com). Затем просуммируем эти комиссии для каждого стилиста (по строкам).

In [40]:
# Расчет суммы комиссии по каждой услуге для каждого стилиста
Commission_Amount_DF = Total_Revenue_DF * com

# Расчет общего дохода салона от каждого стилиста (сумма комиссий по строкам)
Salon_Income_Per_Stylist = Commission_Amount_DF.sum(axis=1)

print("Задание 7.4: Вектор дохода салона по стилистам (тыс. руб.):")
print(Salon_Income_Per_Stylist)
print("-" * 30)

Задание 7.4: Вектор дохода салона по стилистам (тыс. руб.):
Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64
------------------------------


Сравниваем с вариантами ответа:

    1.18,1.36,1.05,1.72,2.05,3.35,1.09,2.75

    9.1,8.6,8.2,9.7,18.6,6.1,10.3,16.6

    11.3,15.22,11.9,20.6,41.9,21.2,11.49,38.25 - Этот вариант совпадает!

    50.2,74.88,59.1,67.8,166.6,113.8,66.21,157.75

Ответ на Задание 7.4: 11.3,15.22,11.9,20.6,41.9,21.2,11.49,38.25

### Задание 7.5
1 point possible (graded)

Найдите вектор дохода стилистов.

Выберите координаты полученного вектора:

Шаг 4: Расчет дохода стилистов (Задание 7.5)

Доход стилиста — это его общая выручка за вычетом комиссии, уплаченной салону.
Сначала найдем общую выручку каждого стилиста, просуммировав Total_Revenue_DF по строкам. Затем вычтем из этой суммы доход салона (комиссию), который мы уже рассчитали (Salon_Income_Per_Stylist).

In [41]:
# Расчет общей выручки каждого стилиста
Total_Gross_Revenue_Per_Stylist = Total_Revenue_DF.sum(axis=1)

# Расчет чистого дохода каждого стилиста
Stylist_Net_Income = Total_Gross_Revenue_Per_Stylist - Salon_Income_Per_Stylist

print("Задание 7.5: Вектор дохода стилистов (тыс. руб.):")
print(Stylist_Net_Income)
print("-" * 30)

Задание 7.5: Вектор дохода стилистов (тыс. руб.):
Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64
------------------------------


Задание 7.5 (Доход стилистов): 
Правильный ответ - 50.2, 74.88, 59.1, 67.8, 166.6, 113.8, 66.21, 157.75.

### Задание 9.8
1/1 point (graded)

Выберите верные утверждения:
![alt text](2025-04-03_21-39-43.png)


In [44]:
import numpy as np

# Определяем векторы
a = np.array([4, 1, 0])
b = np.array([-1, 4, 0])
c = np.array([0, 0, 1])

# Функция для проверки ортогональности двух векторов
def are_orthogonal(v1, v2):
    return np.dot(v1, v2) == 0

# Функция для проверки линейной независимости двух векторов
def are_linearly_independent_2(v1, v2):
    # Для двух векторов: они линейно зависимы, если один пропорционален другому
    # Составим матрицу из этих векторов и проверим ранг
    matrix = np.vstack((v1, v2)).T  # Столбцы — это v1 и v2
    return np.linalg.matrix_rank(matrix) == 2

# Функция для проверки линейной независимости трёх векторов
def are_linearly_independent_3(v1, v2, v3):
    # Составим матрицу из трёх векторов как столбцов
    matrix = np.vstack((v1, v2, v3)).T
    # Если ранг равен 3, то векторы линейно независимы
    return np.linalg.matrix_rank(matrix) == 3

# Проверка утверждения A: есть ли пара ортогональных векторов
orthogonal_ab = are_orthogonal(a, b)
orthogonal_ac = are_orthogonal(a, c)
orthogonal_bc = are_orthogonal(b, c)
statement_A = orthogonal_ab and orthogonal_ac and orthogonal_bc
print("Утверждение A (попарно ортогональны (то есть каждая пара ортогональна)):", statement_A)

# Проверка утверждения B: есть ли пара линейно независимых векторов
independent_ab = are_linearly_independent_2(a, b)
independent_ac = are_linearly_independent_2(a, c)
independent_bc = are_linearly_independent_2(b, c)
statement_B = independent_ab and independent_ac and independent_bc
print("Утверждение B (опарно линейно независимы (то есть каждая пара неколлинеарна)):", statement_B)

# Проверка утверждения C: линейно независимы ли все три вектора
statement_C = are_linearly_independent_3(a, b, c)
print("Утверждение C (все три вектора линейно независимы):", statement_C)

# Итоговый результат
print("\nИтог:")
print("A:", statement_A)
print("B:", statement_B)
print("C:", statement_C)

Утверждение A (попарно ортогональны (то есть каждая пара ортогональна)): True
Утверждение B (опарно линейно независимы (то есть каждая пара неколлинеарна)): True
Утверждение C (все три вектора линейно независимы): True

Итог:
A: True
B: True
C: True
