In [2]:
import numpy as np #для матричных вычислений
import pandas as pd #для анализа и предобработки данных
import matplotlib.pyplot as plt #для визуализации
import seaborn as sns #для визуализации
 
from sklearn import metrics #метрики
from sklearn import model_selection #методы разделения и валидации
from sklearn import linear_model #линейные модели
from sklearn import tree #деревья решений
plt.style.use('seaborn-v0_8') #стиль отрисовки seaborn
%matplotlib inline

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
 
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import r2_score, mean_squared_error, root_mean_squared_error
from sklearn.model_selection import train_test_split, cross_val_score

### Задание 2.5

Ниже представлены доходы семьи за три месяца.

Доходы мужа: 120, 150 и 190 тысяч рублей.
Доходы жены: 130, 130 и 130 тысяч рублей.
Доходы тёщи: 2, 3 и 2.5 тысячи евро.
Вводите координаты полученных векторов через запятую (без пробела). Пример ввода ответа: 0,1,1.

Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.
 
Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам.

In [4]:
income_husband = np.array([120, 150, 190])
income_wife = np.array([130, 130, 130])
income_aunt = np.array([2, 3, 2.5])

curs = 72

income_aunt_rub = income_aunt * curs

display(income_aunt_rub)

income_total = income_husband + income_wife + income_aunt_rub

display(income_total)


array([144., 216., 180.])

array([394., 496., 500.])

### Задание 2.6

1 point possible (graded)

Найдите длину диагонали параллелограмма (сумму векторов), построенного на векторах  a→=(4, 6)  и  b→=(−1, −2) .

5

In [5]:
vector_a = np.array([4, 6])
vector_b = np.array([-1, -2])

vector_sum = vector_a + vector_b

display(vector_sum)

vector_sum_length = np.linalg.norm(vector_sum)

display(vector_sum_length)


array([3, 4])

5.0

В Python линейная комбинация полностью соответствует своему названию и вычисляется как комбинация сложения векторов и умножения вектора на число.


In [7]:

p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u


array([1800, 3000, 2700])

###Задание 2.7

1 point possible (graded)

Найдите линейную комбинацию векторов x→=(4, 5), y→=(2, 1) , u→=(1, 0) с коэффициентами 2, -3 и 5 соответственно.

Пример ввода ответа (через запятую, без пробелов): 0,1.

In [9]:
x = np.array([4, 5])    
y = np.array([2, 1])
u = np.array([1, 0])

omega1 = 2
omega2 = -3
omega3 = 5

u = omega1*x + omega2*y + omega3*u

display(u)


array([7, 7])

### Задание 2.8
1 point possible (graded)
Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.

На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.

Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.

В качестве ответа введите координаты вектора через запятую, без пробелов. Пример ввода ответа: 0,1,1,1.

In [11]:
production = np.array([3, 4, 5, 9])
sales = np.array([1, 5, 3, 6])

cost_per_engine = 200
price_per_engine = 400

profit = price_per_engine * sales - cost_per_engine * production

display(profit)



array([-200, 1200,  200,  600])

В Python скалярное произведение векторов вычисляется при помощи функции np.dot():



In [12]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0