In [1]:
import numpy as np

In [ ]:
# как создать матрицу?

In [2]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [3]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# размер матрицы
np.shape(A)

(4, 3)

In [5]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [6]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [7]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [8]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [ ]:
# создание специальных матриц

In [9]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [14]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [15]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [16]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [17]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [18]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [19]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [20]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [21]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [22]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [23]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [24]:
x_col.T

array([[1, 2, 3]])

In [25]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:



In [26]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

### Задание 5.1

1 point possible (graded)

Составьте матрицу  Inc  доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

100,200,100

In [29]:
#Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T

Inc = np.column_stack([
    Husband_Income,
    Wife_Income,
    Mother_In_Law_Income
])

display(Inc)
display(Inc.diagonal())



array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

array([100, 200, 100])

### Задание 5.2

1 point possible (graded)

Составьте матрицу  Cons  расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

50,80,140

In [30]:
Cons = np.column_stack([
    Husband_Consumption,
    Wife_Consumption,
    Mother_In_Law_Consumption
])

display(Cons)   
display(Cons.diagonal())


array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

array([ 50,  80, 140])

### Задание 5.3

1 point possible (graded)

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу  Inc , где доходы расположены по столбцам.

Выберите список элементов из первой строки этой матрицы (строки нумеруются с 1):

87. , 130.5,  78.3

In [31]:
Inc_wo_tax = Inc * (1-0.13)

display(Inc_wo_tax)
display(Inc_wo_tax[0])


array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

array([ 87. , 130.5,  78.3])

### Задание 5.4

1 point possible (graded)

Вычислите матрицу  P , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

Выберите список элементов из третьей строки этой матрицы:

61.8, -26.9, -53. 

In [32]:
P = Inc_wo_tax - Cons

display(P)
display(P[2])


array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

array([ 61.8, -26.9, -53. ])

![alt text](2025-04-02_16-19-23.png)



In [33]:
import numpy as np

# Определяем матрицы A и B
A = np.array([
    [1, -1, 2, 4, 0],
    [8, 2, 0, 5, 3],
    [0, 1, 2, 1, 2]
])

B = np.array([
    [1, 0, 1, 0],
    [0, 0, 2, -1],
    [0, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 0, -1]
])

# Умножаем матрицы A и B
C = np.dot(A, B)

# Выводим матрицу C
print("Матрица C:")
print(C)

# Находим элементы C12 и C34
# В Python индексация начинается с 0, поэтому C12 -> C[0,1], C34 -> C[2,3]
C12 = C[0, 1]
C34 = C[2, 3]

# Выводим результаты
print(f"C12 = {C12}")
print(f"C34 = {C34}")

Матрица C:
[[ 1  4  5  7]
 [11  8 17  0]
 [ 2  3  5  0]]
C12 = 4
C34 = 0


![alt text](2025-04-02_23-28-14.png)

In [35]:
import numpy as np

# 1. Определяем векторы из условия задачи
# Векторы заданы как столбцы, создадим их как numpy массивы
a = np.array([[1], [1]])
b = np.array([[2], [-1]])
c = np.array([[1], [2]])

# 2. Составляем матрицу A, используя векторы как столбцы
# Функция np.hstack "склеивает" массивы по горизонтали
A = np.hstack((a, b, c))

print("Матрица A:")
print(A)
print(f"Размерность A: {A.shape}") # Должна быть (2, 3)

# 3. Находим транспонированную матрицу Aᵀ
A_T = A.T
# или можно использовать A.transpose()
# A_T = A.transpose()

print("\nТранспонированная матрица Aᵀ:")
print(A_T)
print(f"Размерность Aᵀ: {A_T.shape}") # Должна быть (3, 2)

# 4. Вычисляем матрицу Грама G = Aᵀ * A
# Используем оператор @ для матричного умножения (или np.matmul)
G = A_T @ A
# G = np.matmul(A_T, A)

print("\nМатрица Грама G = Aᵀ * A:")
print(G)
print(f"Размерность G: {G.shape}") # Должна быть (3, 3)

# 5. Сравним результат с вариантами ответов

# Варианты ответов (для наглядности)
option1 = np.array([[3, 4, 8], [4, -1, 0], [8, 0, -1]])
option2 = np.array([[1, 2, 1], [1, -1, 2]]) # Неверная размерность
option3 = np.array([[6, 1], [1, 6]])       # Неверная размерность
option4 = np.array([[2, 1, 3], [1, 5, 0], [3, 0, 5]])

print("\nСравнение с вариантами:")
print("Вариант 1:\n", option1)
print("Совпадает?", np.array_equal(G, option1))

# Сравнение с остальными не имеет смысла из-за размерности, но для полноты:
print("\nВариант 2:\n", option2)
print("Совпадает?", np.array_equal(G, option2)) # Ошибка из-за размерности
print("\nВариант 3:\n", option3)
print("Совпадает?", np.array_equal(G, option3)) # Ошибка из-за размерности

print("\nВариант 4:\n", option4)
print("Совпадает?", np.array_equal(G, option4))

print("\n-----------------------------")
print("Правильный ответ - Вариант 4.")

Матрица A:
[[ 1  2  1]
 [ 1 -1  2]]
Размерность A: (2, 3)

Транспонированная матрица Aᵀ:
[[ 1  1]
 [ 2 -1]
 [ 1  2]]
Размерность Aᵀ: (3, 2)

Матрица Грама G = Aᵀ * A:
[[2 1 3]
 [1 5 0]
 [3 0 5]]
Размерность G: (3, 3)

Сравнение с вариантами:
Вариант 1:
 [[ 3  4  8]
 [ 4 -1  0]
 [ 8  0 -1]]
Совпадает? False

Вариант 2:
 [[ 1  2  1]
 [ 1 -1  2]]
Совпадает? False

Вариант 3:
 [[6 1]
 [1 6]]
Совпадает? False

Вариант 4:
 [[2 1 3]
 [1 5 0]
 [3 0 5]]
Совпадает? True

-----------------------------
Правильный ответ - Вариант 4.


In [37]:
import numpy as np

# 1. Определяем векторы из условия задачи
a = np.array([[1], [1]])
b = np.array([[2], [-1]])
c = np.array([[1], [2]])

# 2. Составляем матрицу A, используя векторы как столбцы
A = np.hstack((a, b, c))

print("Матрица A:")
print(A)
print(f"Размерность A: {A.shape}") # (2, 3)

# 3. Находим транспонированную матрицу Aᵀ
A_T = A.T

print("\nТранспонированная матрица Aᵀ:")
print(A_T)
print(f"Размерность Aᵀ: {A_T.shape}") # (3, 2)

# 4. Вычисляем матрицу Грама G = Aᵀ * A
G = A_T @ A

print("\nВычисленная матрица Грама G = Aᵀ * A:")
print(G)
print(f"Размерность G: {G.shape}") # (3, 3)

# 5. Определяем варианты ответов из задания
options = {
    1: np.array([[3, 4, 8], [4, -1, 0], [8, 0, -1]]),
    2: np.array([[1, 2, 1], [1, -1, 2]]),
    3: np.array([[6, 1], [1, 6]]),
    4: np.array([[2, 1, 3], [1, 5, 0], [3, 0, 5]])
}

# 6. Программно находим правильный вариант
correct_option_number = None
correct_option_matrix = None

print("\nСравнение вычисленной матрицы G с вариантами:")
for number, matrix in options.items():
    print(f"--- Вариант {number} ---")
    print(matrix)
    # Сначала проверяем совпадение размерностей, затем равенство матриц
    if G.shape == matrix.shape and np.array_equal(G, matrix):
        correct_option_number = number
        correct_option_matrix = matrix
        print("--> Совпадает!")
        # Можно добавить break, если уверены, что правильный ответ только один
        # break
    else:
        print("--> Не совпадает.")


# 7. Выводим результат проверки
print("\n-----------------------------")
if correct_option_number is not None:
    print(f"Вычисления показывают, что правильный ответ - Вариант {correct_option_number}.")
    # Можно еще раз вывести матрицу для наглядности, если нужно
    print("Матрица правильного варианта:")
    print(correct_option_matrix)
else:
    # Эта ситуация не должна возникнуть, если один из вариантов верный
    print("Не удалось найти совпадающий вариант среди предложенных.")
print("-----------------------------")

Матрица A:
[[ 1  2  1]
 [ 1 -1  2]]
Размерность A: (2, 3)

Транспонированная матрица Aᵀ:
[[ 1  1]
 [ 2 -1]
 [ 1  2]]
Размерность Aᵀ: (3, 2)

Вычисленная матрица Грама G = Aᵀ * A:
[[2 1 3]
 [1 5 0]
 [3 0 5]]
Размерность G: (3, 3)

Сравнение вычисленной матрицы G с вариантами:
--- Вариант 1 ---
[[ 3  4  8]
 [ 4 -1  0]
 [ 8  0 -1]]
--> Не совпадает.
--- Вариант 2 ---
[[ 1  2  1]
 [ 1 -1  2]]
--> Не совпадает.
--- Вариант 3 ---
[[6 1]
 [1 6]]
--> Не совпадает.
--- Вариант 4 ---
[[2 1 3]
 [1 5 0]
 [3 0 5]]
--> Совпадает!

-----------------------------
Вычисления показывают, что правильный ответ - Вариант 4.
Матрица правильного варианта:
[[2 1 3]
 [1 5 0]
 [3 0 5]]
-----------------------------
