In [1]:
import numpy as np #для матричных вычислений
import pandas as pd #для анализа и предобработки данных


### Задание 1.1

1 point possible (graded)

Найдите скалярное произведение векторов:


In [2]:
# Определяем векторы
v1 = np.array([-1, 2, -7, 9])
v2 = np.array([2, 8, 2, -1])

print('Скалярное произведение вектороа v1 и v2 :',np.dot(v1,v2))

Скалярное произведение вектороа v1 и v2 : -9


### Задание 1.4
4 points possible (graded)
Задана матрица

A=(1, 1
   1, 2)

Найдите матрицу Грама ATA.

Заполните текстовые поля слева направо, сверху вниз.

In [5]:
v1 = np.array([1, 1])
v2 = np.array([1, 2])

A = np.array([v1,v2]).T
print('Матрица А:\n',A)

G = A.T@A

print('Матрица Грама:\n',G)


Матрица А:
 [[1 1]
 [1 2]]
Матрица Грама:
 [[2 3]
 [3 5]]


### Задание 1.6

4 points possible (graded)

Вычислите обратную матрицу A−1, если:

A=(1, 3,
   2, 7)

Заполните текстовые поля слева направо, сверху вниз.


In [8]:
v1 = np.array([1, 3])
v2 = np.array([2, 7])

A = np.array([v1,v2]).T
print('A        :\n',A)

print('A inverse:\n',np.linalg.inv(A))

A        :
 [[1 2]
 [3 7]]
A inverse:
 [[ 7. -2.]
 [-3.  1.]]


### Задание 1.7

1 point possible (graded)

Найдите ранг матрицы системы, составленной из векторов:

v1→=(2,10,−2)T

v2→=(3,2,−2)T

v3→=(8,14,−6)T


2

In [10]:
v1 = np.array([2, 10, -2])

v2 = np.array([3, 2, -2])

v3 = np.array([8, 14, -6])

A = np.array([v1,v2,v3]).T

print('A        :\n',A)

print('rk(A):\n',np.linalg.matrix_rank(A))

A        :
 [[ 2  3  8]
 [10  2 14]
 [-2 -2 -6]]
rk(A):
 2


### Задание 1.8

1 point possible (graded)

Определите линейную (не)зависимость системы векторов:

v1→=(2,10,−2)T

v2→=(3,2,−2)T

v3→=(8,14,−6)T

Система векторов является линейно зависимой

Ответ
Верно:Как следует из предыдущего задания, ранг системы равен 2, что меньше количества векторов в системе, а значит вектора являются линейно зависимыми.

In [11]:
v1 = np.array([2, 10, -2])

v2 = np.array([3, 2, -2])

v3 = np.array([8, 14, -6])

A = np.array([v1,v2,v3]).T

print('A        :\n',A)

print('Размерность матрицы A:', A.shape)

print('rk(A):\n',np.linalg.matrix_rank(A))

A        :
 [[ 2  3  8]
 [10  2 14]
 [-2 -2 -6]]
Размерность матрицы A: (3, 3)
rk(A):
 2


### Задание 1.9

1 point possible (graded)

Сколько нетривиальных решений имеет представленная ниже система уравнений?

5w1+w2=0
10w1+2w2=0

Бесконечное множество решений

Перед нами однородная СЛАУ. Такие СЛАУ имеют только два случая решений:

Бесконечное множество решений, если уравнения являются пропорциональными другу, то есть ранг матрицы системы  A  меньше количества неизвестных.
Не имеет решений, если уравнения не являются пропорциональными, то есть ранг матрицы системы  A  равен количеству неизвестных.
Видно, что уравнения в нашей системе пропорциональны друг другу: если умножить первое на 2, получится второе уравнение, а значит одно из них можно убрать. Тогда останется только одно уравнение на две неизвестных:

5w1+w2=0 

Таким образом, количество неизвестных (2) больше, чем количество линейно независимых уравнений, или ранг матрицы (1), а значит система имеет бесконечное множество решений.

In [13]:
v1 = np.array([5, 10])

v2 = np.array([1, 2])

A = np.array([v1,v2]).T

print('A        :\n',A)

print('det(A):\n',np.linalg.det(A))
print('rk(A):\n',np.linalg.matrix_rank(A))

A        :
 [[ 5  1]
 [10  2]]
det(A):
 0.0
rk(A):
 1


### Задание 2.9

1 point possible (graded)

Вычислите вектор ошибок  e  для приближённого решения системы уравнений:
![alt text](2025-04-04_00-24-55.png)


In [15]:
import numpy as np

# Определяем матрицу A и вектор b
A = np.array([[1, -5],
              [2, 1],
              [1, 1]])
b = np.array([1, 2, 2])

# Приближенное решение
w = np.array([1, 1])

# Вычисляем b'
b_prime = A @ w

# Вычисляем вектор ошибок e
e = b - b_prime

print(f"Матрица A:\n{A}")
print(f"Вектор b:\n{b}")
print(f"Приближенное решение w:\n{w}")
print(f"Вычисленное b' = A * w:\n{b_prime}")
print(f"Вектор ошибок e = b - b':\n{e}")

Матрица A:
[[ 1 -5]
 [ 2  1]
 [ 1  1]]
Вектор b:
[1 2 2]
Приближенное решение w:
[1 1]
Вычисленное b' = A * w:
[-4  3  2]
Вектор ошибок e = b - b':
[ 5 -1  0]


### Задание 2.11

7/7 points (graded)

Найдите OLS-оценку для коэффициентов w1, w2 СЛАУ:

![alt text](2025-04-04_08-42-32.png)

In [17]:
import numpy as np
from fractions import Fraction

# Определяем матрицу A и вектор b
A = np.array([[1, 2],
              [-3, 1],
              [1, 2],
              [1, -1]])
b = np.array([1, 4, 5, 0])

# 1. Вычисляем A^T A
ATA = A.T @ A
print("1. Матрица A^T A:")
print(ATA)

# 2. Вычисляем (A^T A)^(-1)
ATA_inv = np.linalg.inv(ATA)
print("\n2. Матрица (A^T A)^(-1):")
print(ATA_inv)

# 3. Вычисляем A^T b
ATb = A.T @ b
print("\nA^T b:")
print(ATb)

# 4. Вычисляем OLS-оценку w = (A^T A)^(-1) * (A^T b)
w = ATA_inv @ ATb
print("\nOLS-оценка w:")
print(w)

# 5. Преобразуем w в дроби и выводим
w_fractions = [Fraction(x).limit_denominator() for x in w]
print(f"\nOLS-оценка в дробях: w1 = {w_fractions[0]}, w2 = {w_fractions[1]}")

1. Матрица A^T A:
[[12  0]
 [ 0 10]]

2. Матрица (A^T A)^(-1):
[[0.08333333 0.        ]
 [0.         0.1       ]]

A^T b:
[-6 16]

OLS-оценка w:
[-0.5  1.6]

OLS-оценка в дробях: w1 = -1/2, w2 = 8/5
